parameters:
#    support.example.class: SiQ\SupportBundle\Example

services:
#    support.example:
#        class: %support.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


      SiQ_support.antispam:
           class: SiQ\SupportBundle\Antispam\TicketAntispam
#        arguments: [@mailer, "locale", 3]